### ISSUE TITLE
Double ££ in the vehicle shop.

### ISSUE THREAD

**Issue by CapGamNet** [SimZor/A3RPGFramework#3]
[Double ££ in the vehicle shop.](https://cdn.discordapp.com/attachments/437700677360156682/438781182067343360/unknown.png)

**Comment by FallenUK** [comment]
This issue has now been resolved.

**Comment by CapGamNet** [comment]
Police Vehicles still have ££.

**Comment by FallenUK** [comment]
@capwell can I please get a screenshot please.

**Comment by CapGamNet** [comment]
Sure, let just get out of my vehicle. Oh wait, I cannot.. :(

**Comment by FallenUK** [comment]
This issue has now been resolved.
