### ISSUE TITLE
PLEASE READ BEFORE POSTING ISSUE(S)

### ISSUE THREAD

**Issue by d3xy** [SimZor/A3RPGFramework#4]
Hello everyone, 
thanks for taking your time and reading through this post, as we all know that this Framework comes as is and was completely built from scratch, even though countless hours have been put in the development and testing of the framework, there still are some bugs that need to be fixed, with that being said we would appreciate if the following formate below is used to report the issues, this will ensure that every detail is provided which further helps with tracking of the issue and fixing it in the most efficient way possible.

Title; The issue.
Body; The issue explained in detail.
Evidence of issue;  (its not a must but helps with the tracking and reproducing)
Steps to reproduce;  Step 1.
                                  Step 2.
                                  Step 3.

Once again thank you for reading through this post, posting in the formate above will help the maintainers track down the issue and fix it as soon as possible in the most efficient way possible.

**Comment by SimZor** [comment]
Making a template.
